---
stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
  paths:
    - .cache

.build: &build
  stage: build
  tags:
    - build
  script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - go mod download
    - go build ./cmd/vault-secret-broker
  artifacts:
    expire_in: 24 h
    paths:
      - vault-secret-broker

build-1.11:
  <<: *build
  before_script:
    - apk add --no-cache git build-base
  image: registry-group.mgmtbi.ch/golang:1.11-alpine

build-1.12:
  <<: *build
  before_script:
    - apk add --no-cache git
  image: registry-group.mgmtbi.ch/golang:1.12-alpine

build-1.13:
  <<: *build
  image: registry-group.mgmtbi.ch/golang:1.13-alpine