---
stages:
  - build:docker

.docker-base:
  stage: build:docker
  image:
    name: registry-group.mgmtbi.ch/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - build
  before_script:
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
    - PROXY="--build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --build-arg no_proxy=${no_proxy}"
    - REGISTRY="--build-arg DOCKER_REGISTRY=registry-group.mgmtbi.ch/"
    - GO_VERSION="--build-arg GO_VERSION=1.13"

build:docker:dev:
  extends: .docker-base
  script:
    - /kaniko/executor --context="$CI_PROJECT_DIR" --dockerfile="$CI_PROJECT_DIR/Dockerfile" --destination="${DOCKER_REGISTRY}/bedag_dcs/vault-secret-broker/dev:${CI_COMMIT_REF_SLUG}" --reproducible --single-snapshot ${PROXY} ${REGISTRY} ${GO_VERSION}
  only:
    - branches
  except:
    - master

build:docker:master:
  extends: .docker-base
  script:
    - /kaniko/executor --context="$CI_PROJECT_DIR" --dockerfile="$CI_PROJECT_DIR/Dockerfile" --destination="${DOCKER_REGISTRY}/bedag_dcs/vault-secret-broker:latest" --reproducible --single-snapshot ${PROXY} ${REGISTRY} ${GO_VERSION}
  only:
    - master
  except:
    - tags