FROM {{ _source["name"] }}:{{ _source["tag"] }}
MAINTAINER {{ maintainer }}

LABEL \{% for tag in _dest['tags']|map('replace','.','_')|list %}
  "tag.{{ tag }}.repository"="{{ _dest['namespace'] }}/{{ _dest['name'] }}" \
  "tag.{{ tag }}.source"="{{ _source["name"] }}:{{ _source["tag"] }}" \
  "tag.{{ tag }}.git.repo"="{{ git_repo }}" \
  "tag.{{ tag }}.git.ref"="{{ git_ref }}" \
  "tag.{{ tag }}.git.commit"="{{ git_commit }}" \
{%- endfor %}
  "maintainer"="{{ maintainer }}"

RUN addgroup -S broker && adduser -S -g broker broker
USER broker

COPY vault-secret-broker /

ENTRYPOINT ["/sbin/tini", "--", "/vault-secret-broker"]
CMD ["serve"]

EXPOSE 8080/tcp
EXPOSE 8443/tcp